version: "3.9"

services:
  document-service:
    restart: always
    environment:
      DEBUG: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  auth-service:
    restart: always
    environment:
      DEBUG: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  notification-service:
    restart: always
    environment:
      DEBUG: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    restart: always
    environment:
      DEBUG: "false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    restart: always
    ports: []
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: always
    ports: []
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    restart: always
    ports: []

  grafana:
    restart: always
    ports: []
