apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservice-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: maskamyll/mindcampus-api-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: secret-key
            - name: APP_NAME
              value: "api-gateway"
            - name: DEBUG
              value: "false"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8000"
            - name: DOCUMENT_SERVICE_URL
              value: "http://document-service:8000"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:8000"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
