apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservice-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: maskamyll/mindcampus-api-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: secret-key
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: redis-url
            - name: APP_NAME
              value: "api-gateway"
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: APP_VERSION
            - name: DEBUG
              value: "false"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: AUTH_SERVICE_URL
            - name: DOCUMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: DOCUMENT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: NOTIFICATION_SERVICE_URL
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: CORS_ORIGINS
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
